POST http://localhost:4004/odata/v4/product/Invoice_Details
Content-Type: application/json

{
    "Configurations": [
        {
            "ID_Configuration": "16625531-d167-4462-8077-bd3f422830f7",
            "ID_Mobile_ID_Mobile": "6d4b5141-2279-43ef-bea4-ba008d6062f9",
            "Config_Name": "iPhone 12",
            "RAM": "4GB",
            "Storage": "64GB",
            "Processor": "A14 Bionic",
            "Display": "6.1",
            "Battery": "2815mAh",
            "Config_Price": 799,
            "Stock": 50
        },
        {
            "ID_Configuration": "26a02eb0-dbb3-4bfb-9030-7c09fbd4b25c",
            "ID_Mobile_ID_Mobile": "8d847065-f735-409d-a048-567f35af296e",
            "Config_Name": "iPhone 11",
            "RAM": "4GB",
            "Storage": "64GB",
            "Processor": "A13 Bionic",
            "Display": "6.1",
            "Battery": "3110mAh",
            "Config_Price": 599,
            "Stock": 60
        },
        {
            "ID_Configuration": "309ffaff-101a-4f8b-b53b-682a75539c6e",
            "ID_Mobile_ID_Mobile": "0771e0fe-d687-4087-8265-df18c9f68c59",
            "Config_Name": "iPhone 12 Pro Max",
            "RAM": "6GB",
            "Storage": "128GB",
            "Processor": "A14 Bionic",
            "Display": "6.7",
            "Battery": "3687mAh",
            "Config_Price": 1099,
            "Stock": 35
        }
    ]
}